#!/bin/sh
#
# Re-used example from SJD
#

set -e

stamp="$COSMOS_BASE/stamps/ansible-v01.stamp"

if ! test -f "${stamp}" -a -f /usr/bin/pip3; then
    apt-get update
    apt-get -y install python3-pip
    . /etc/os-release
    python3 -m pip install ansible==9.1.0 --user

    git clone https://github.com/kushaldas/simpleansible.git

    mkdir -p "$(dirname "${stamp}")"
    touch "${stamp}"
fi

